### ISSUE TITLE
Fading a led in void setup()

### ISSUE THREAD

**Issue by moracabanas** [jgillick/arduino-LEDFader#5]
Hi, im a newbie writing code :'D. Im making an RFID door unlocker. I replace the RGB blinking led by a single white led with awesome fade. Im trying to call some methods I created before to fade a led with easy effects from this great library but im having some difficulties to get it working correctly. I can upload the full code where I have the issue but here's an example: 

This is a method i created from a bit modified "example" from wiki:

``` c++
#include <LEDFader.h>


#define FADE_TIME    1000 //(miliseconds)
#define INTENSITY     200  // Intensity

void fadeLed(){
 if (led.is_fading() == false) {

    // Fade from 255 - 0
    if (led.get_value() == INTENSITY) {
      led.fade(0, FADE_TIME);
    }
    // Fade from 0 - 255
    if (led.get_value() == 0) {
      delay(200);
      led.fade(INTENSITY, FADE_TIME);
    }
  }
}
```

When i try to run this:

``` c++
#include <LEDFader.h>


#define FADE_TIME    1000 //(miliseconds)
#define INTENSITY     200  // Intensity



// Create new LED Fader on pin 5
LEDFader led = LEDFader(5);


void setup() {
fadeLed();

}

void loop() {
  led.update();

}


void fadeLed(){
 if (led.is_fading() == false) {

    // Fade from INTENSITY - 0
    if (led.get_value() == INTENSITY) {
      led.fade(0, FADE_TIME);
    }
    // Fade from 0 - INTENSITY
    if (led.get_value() == 0) {
      delay(200);
      led.fade(INTENSITY, FADE_TIME);
    }
  }
}
```

I get led fading from 0 to 255 but it gets stuck there. If I call `fadeLed()` in `void loop()` it works.

I wondering how to run methods like this on `void setup()`. 
Here's the full code where i have the issue(not complete and in a partial Spanish translation, sorry about that: 
https://www.dropbox.com/s/azdpxl1pm2cdlkf/RFID_RC522_Door_LED_BLANCO.ino?dl=0

**Comment by jgillick** [comment]
`setup` is only ever called once, so your `fadeLed` method will only be run once. In fact, the only thing it will do in this example is start fading from 0 - 200 and then the fade library will automatically stop it at 200. Since the function is never called again, it will never start the fade from 200 to 0. `loop` is where you want to put this function call:

```
void loop() {
  led.update();
  fadeLed();
}
```

How `loop` works is it executes everything in that function, one at a time. When it gets to the bottom of the function, it starts again from the first line. So with put `led.update()` and `fadeLed()` in `loop`, execution will look like this:

```
-- setup() --
  (anything you put in that function)
-- loop() --
  led.update();
  fadeLed();

  led.update();
  fadeLed();

  led.update();
  fadeLed();

  led.update();
  fadeLed();

  // forever
